steps:
  - name: "gcr.io/kaniko-project/executor:v1.8.0"
    args:
      - --destination=$_GCR_HOSTNAME/$PROJECT_ID/yoda-ner-api/$_SERVICE_NAME
      - --cache=true
      - --snapshotMode=redo

timeout: 1200s
