steps:
  - name: "gcr.io/kaniko-project/executor:v1.8.0"
    args:
      - --destination=$_GCR_HOSTNAME/$PROJECT_ID/yoda-ner-api/$_SERVICE_NAME:latest
      - --cache=true
      - --verbosity=debug
      - --snapshotMode=redo
      - --use-new-run

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - run
      - deploy
      - $_SERVICE_NAME
      - --image=$_GCR_HOSTNAME/$PROJECT_ID/yoda-ner-api/$_SERVICE_NAME:latest
      - --platform=managed
      - --region=europe-west1
      - --allow-unauthenticated
      - --project=$PROJECT_ID
      - --verbosity=debug
      - --quiet

timeout: 1200s
