steps:
  - timeout: 1200s
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --network=host
      - --pull
      - -t
      - gcr.io/$PROJECT_ID/yoda-ner-api:latest
      - .

timeout: 1200s

images: ["gcr.io/$PROJECT_ID/yoda-ner-api:latest"]
