steps:
  - timeout: 1200s
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --network=host
      - --pull
      - -t
      - $_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:latest
      - .

timeout: 1200s

images: ["$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:latest"]
