steps:
  - timeout: 1200s
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - "$_GCR_HOSTNAME/$PROJECT_ID/yoda-ner-api/$_SERVICE_NAME:latest"
      - "--cache-from"
      - "$_GCR_HOSTNAME/$PROJECT_ID/yoda-ner-api/$_SERVICE_NAME:latest"
      - .

timeout: 1200s

images: ["$_GCR_HOSTNAME/$PROJECT_ID/yoda-ner-api/$_SERVICE_NAME:latest"]
