steps:
  - timeout: 1200s
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --network=host
      - --pull
      - -t
      - ${_IMAGE_NAME}
      - .

images: ["${_IMAGE_NAME}"]

substitutions:
  _IMAGE_NAME: "gcr.io/$PROJECT_ID/$REPO_NAME@sha256:$COMMIT_SHA"
