steps:
  - timeout: 1200s
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --network=host
      - --pull
      - -t
      - gcr.io/$PROJECT_ID/$REPO_NAME@sha256:$COMMIT_SHA
      - .

images: ["gcr.io/$PROJECT_ID/$REPO_NAME@sha256:$COMMIT_SHA"]